<?php
// +----------------------------------------------------------------------
// | Title   : 基础类
// +----------------------------------------------------------------------
// | Created : Henrick (me@hejinmin.cn)
// +----------------------------------------------------------------------
// | From    : Shenzhen wepartner network Ltd
// +----------------------------------------------------------------------
// | Date    : 2019-11-04 15:18
// +----------------------------------------------------------------------


namespace app\common\controller;


use app\BaseController;
use app\common\middleware\AuthMid;
use think\middleware\AllowCrossDomain;

class PmsApiController extends BaseController
{
    /**
     * 用户ID
     * @var string
     */
    protected $userId = "";
    /**
     * 用户信息
     * @var array
     */
    protected $userInfo = [];

    protected $middleware = [
        AllowCrossDomain::class
    ];

    /**
     * 错误提醒 - json返回
     * @param int $code
     * @param string $msg
     * @param array $data
     * @return \think\response\Json
     */
    protected function _error($code=0, $msg='成功', $data=[]){
        $data = empty($data)? (object)$data:$data;
        return json(['errcode'=> $code, 'errmsg' => $msg, 'data' => $data])->send();
    }

    public function initialize()
    {
        $sessionKey = $this->request->header('session_key');
        //sessionKey不存在则说明未登录
        if(!$sessionKey){
            return $this->_error(100, '请登录后操作~');
        }
        $devType = $this->request->header('dev');
        $sessionKey = $devType."_".$sessionKey;
        //登录失效
        if(!$userInfo = cache($sessionKey)){
            return $this->_error(100, '登录已失效，请重新登录~');
        }
        $this->userId = $userInfo['id'];
        $this->userInfo = $userInfo;
        return parent::initialize(); // TODO: Change the autogenerated stub
    }
}