<?php
declare (strict_types = 1);

namespace app\pms\controller;

use app\common\controller\PmsApiController;

class UserController extends PmsApiController
{
    /**
     * @var 用户服务模型
     */
    private $_userService;

    public function initialize()
    {
        $this->_userService = invoke('app\common\service\UserService');
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录接口
     * @return \think\Response
     */
    public function loginAction()
    {
        if($this->request->isPost()){
            $res = $this->_userService->login($this->request->post());
            return static::_error($res['errcode'], $res['errmsg']);
        }
        return static::_error(1, '无法访问此方法');
    }


}
